version: '3.8'

services:
  jenkins:
    build:
      context: .
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    group_add:
      - "${DOCKER_GID}"
    environment:
      - PATH=/root/.cargo/bin:$PATH

volumes:
  jenkins_home:
